### ISSUE TITLE
Are you able to use it for alignment of selected text?

### ISSUE THREAD

**Issue by JMA12** [webdeveloperpr/draft-js-custom-styles#17]
Can this be used for alignment of selected texts?

**Comment by steveostudios** [comment]
@JMA12 I couldn't figure out how to do this. I spent a day trying to do this as well. I think the reason you _may not_ be able to to it is because this library applies styles _inline_, and aligning texts needs to be placed on the _block_ level. To me it doesn't look like this applies styles to a block. Luckily Draft JS does do block styling! (https://draftjs.org/docs/advanced-topics-block-styling). 

Hope that helps!

**Comment by betancourtl** [comment]
I haven't used this in a very very long time, if I remember correctly @steveostudios is right, you need to  style blocks using the `blockStyleFn`

**Comment by JMA12** [comment]
Thanks @steveostudios  and @webdeveloperpr 

Already found the solution using toggleBlockType function from RichUtils.
